[package]
name = "hamming"
version = "0.1.2"
authors = ["Huon Wilson <dbau.pp@gmail.com>"]

license = "MIT/Apache-2.0"
keywords = ["popcount", "hamming", "bithack"]
homepage = "https://github.com/huonw/hamming"
repository = "https://github.com/huonw/hamming"
documentation = "http://huonw.github.io/hamming/hamming/"

description = """
Count ones, fast (aka popcount, hamming weight). This provides a
performant popcount and bitwise hamming distance for a slice of bytes.
"""

[features]
unstable = []
simd = ["faster"]

[dependencies]
faster = { git = "https://github.com/AdamNiederer/faster", branch = "master", optional = true }

[dev-dependencies]
quickcheck = "0.2"
rand = "0.3"
